# a simple test run
/run/initialize

/gps/particle gamma
/gps/ene/type Bbody
# /gps/ene/temp 5778 K # Sol
/gps/ene/temp 5100 K   # Sol en Tierra
/gps/ene/min 0.496 eV  # Energía mínima correspondiente a 2500 nm
/gps/ene/max 12.4 eV   # Energía máxima correspondiente a 100 nm
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 2.5 cm
/gps/pos/centre 0 0 -5 cm  # Centro del círculo en (0, 0, -5 cm)
/gps/direction 0 0 1        # Dirección de las partículas a lo largo del eje Z
/gps/ene/calculate
/run/beamOn 1000000

